export const POKEMONS_TIPO_REQUEST = "POKEMONS_TIPO_REQUEST";
export const POKEMONS_TIPO_SUCCESS = "POKEMONS_TIPO_SUCCESS";
export const POKEMONS_TIPO_ERROR = "POKEMONS_TIPO_ERROR";
export const LIMPA_POKEMONS_TIPO = "LIMPA_POKEMONS_TIPO";